# Generated by Django 2.0 on 2018-02-22 16:43

import crud.models
import crud.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.translation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=None, null=True, verbose_name='Grade')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('retake', models.BooleanField(default=False, verbose_name='Retake')),
            ],
            options={
                'verbose_name': 'Grade',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Name')),
                ('year', models.SmallIntegerField(default=2018, verbose_name='Year')),
                ('regular_grades_num', models.SmallIntegerField(default=crud.models.get_default_grades_num, verbose_name='Number of regular grades')),
                ('retake_grades_num', models.SmallIntegerField(default=crud.models.get_default_retake_num, verbose_name='Number of retakes')),
                ('avg', models.FloatField(default=crud.models.get_default_avg, verbose_name='Average to get approved')),
            ],
            options={
                'verbose_name': 'Class',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_avg', models.FloatField(default=7.0, verbose_name='Default average')),
                ('default_grades_num', models.SmallIntegerField(default=3, verbose_name='Default number of regular grades')),
                ('default_retake_num', models.SmallIntegerField(default=1, verbose_name='Default number of retake grades')),
                ('lang', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese (Brazil)')], default=django.utils.translation.get_language, max_length=25, null=True, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('phone', models.CharField(max_length=11, verbose_name='Telephone number')),
                ('registry', models.SlugField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Registry')),
                ('birth', models.DateField(null=True, verbose_name='Birth date')),
                ('document', models.FileField(upload_to=crud.utils.documentPath, verbose_name='ID Document')),
            ],
            options={
                'verbose_name': 'Student',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='crud.SchoolClass', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Subject',
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='crud.Student', verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='crud.Student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='crud.Subject'),
        ),
    ]
