# Generated by Django 2.0 on 2018-01-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('id_document', models.CharField(max_length=30, verbose_name='ID Document')),
                ('registry', models.CharField(max_length=30, verbose_name='Registry')),
                ('birth', models.DateField(verbose_name='Birth Date')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Class')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('grade1', models.FloatField(default=0, verbose_name='Grade 1')),
                ('grade2', models.FloatField(default=0, verbose_name='Grade 2')),
                ('grade3', models.FloatField(default=0, verbose_name='Grade 3')),
                ('grade4', models.FloatField(default=0, verbose_name='Grade 4')),
                ('rec', models.FloatField(default=0, verbose_name='Recuperation')),
                ('partial_avg', models.FloatField(default=0, verbose_name='Partial average')),
                ('total_avg', models.FloatField(default=0, verbose_name='Total average')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Student')),
            ],
            options={
                'verbose_name': 'Subject',
            },
        ),
    ]
