# Generated by Django 2.0 on 2018-01-28 13:55

import crud.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='Grade')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('retake', models.BooleanField(default=False, verbose_name='Retake')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Class')),
            ],
            options={
                'verbose_name': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.FloatField(verbose_name='Average')),
                ('lang', models.CharField(choices=[(('pt-br', 'Portuguese (Brazil)'), ('en', 'English')), (('pt-br', 'Portuguese (Brazil)'), ('en', 'English'))], max_length=25, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('phone', models.CharField(max_length=11, verbose_name='Telephone number')),
                ('registry', models.SlugField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Registry')),
                ('birth', models.DateField(null=True, verbose_name='Birth date')),
                ('document', models.FileField(upload_to=crud.utils.documentPath, verbose_name='ID Document')),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Class')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Class')),
            ],
            options={
                'verbose_name': 'Subject',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Subject'),
        ),
    ]
