# Generated by Django 2.0 on 2018-01-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_document',
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade1',
            field=models.FloatField(null=True, verbose_name='Grade 1'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade2',
            field=models.FloatField(null=True, verbose_name='Grade 2'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade3',
            field=models.FloatField(null=True, verbose_name='Grade 3'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade4',
            field=models.FloatField(null=True, verbose_name='Grade 4'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='rec',
            field=models.FloatField(null=True, verbose_name='Recuperation'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Student'),
        ),
    ]
