# Generated by Django 2.0 on 2018-01-23 18:17

import crud.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.FileField(upload_to=crud.utils.documentPath, verbose_name='ID Document'),
        ),
    ]
