# Generated by Django 2.0 on 2018-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20180105_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.FloatField(verbose_name='Average')),
                ('lang', models.CharField(max_length=25, verbose_name='Language')),
            ],
        ),
    ]
