# Generated by Django 2.0 on 2018-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20180123_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registry',
            field=models.SlugField(max_length=30, verbose_name='Registry'),
        ),
    ]
