# Generated by Django 2.0 on 2018-02-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20180201_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='value',
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.SmallIntegerField(default=2018, verbose_name='Year'),
        ),
    ]
