# Generated by Django 2.0 on 2018-02-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20180202_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='school_class',
        ),
    ]
