# Generated by Django 2.0 on 2018-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20180203_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('-year',), 'verbose_name': 'Class'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='class',
            name='student_body',
            field=models.ManyToManyField(related_name='classes', to='crud.Student', verbose_name='Students'),
        ),
    ]
