# Generated by Django 2.0 on 2018-02-08 12:57

import crud.models
from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20180205_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='avg',
        ),
        migrations.AddField(
        model_name='settings',
        name='default_grades_num',
        field=models.SmallIntegerField(default=3, verbose_name='Default number of regular grades'),
        ),
        migrations.AddField(
        model_name='settings',
        name='default_retake_num',
        field=models.SmallIntegerField(default=1, verbose_name='Default number of retake grades'),
        ),
        migrations.AlterField(
        model_name='settings',
        name='lang',
        field=models.CharField(choices=[(('pt-br', 'Portuguese (Brazil)'), ('en', 'English')), (('pt-br', 'Portuguese (Brazil)'), ('en', 'English'))], default=django.utils.translation.get_language, max_length=25, verbose_name='Language'),
        ),
        migrations.AddField(
        model_name='settings',
        name='default_avg',
        field=models.FloatField(default=7.0, verbose_name='Default average'),
        ),
        migrations.AddField(
            model_name='class',
            name='avg',
            field=models.FloatField(default=crud.models.get_default_avg, verbose_name='Average to get approved'),
        ),
        migrations.AddField(
            model_name='class',
            name='regular_grades_num',
            field=models.SmallIntegerField(default=crud.models.get_default_retake_num, verbose_name='Number of regular grades'),
        ),
        migrations.AddField(
            model_name='class',
            name='retake_grades_num',
            field=models.SmallIntegerField(default=crud.models.get_default_grades_num, verbose_name='Number of retakes'),
        ),
    ]
