# Generated by Django 2.0 on 2018-02-08 13:10

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20180208_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='lang',
            field=models.CharField(choices=[(('pt-br', 'Portuguese (Brazil)'), ('en', 'English')), (('pt-br', 'Portuguese (Brazil)'), ('en', 'English'))], default=django.utils.translation.get_language, max_length=25, null=True, verbose_name='Language'),
        ),
    ]
