# Generated by Django 2.0 on 2018-02-08 13:43

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20180208_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='regular_grades_num',
            field=models.SmallIntegerField(default=crud.models.get_default_grades_num, verbose_name='Number of regular grades'),
        ),
        migrations.AlterField(
            model_name='class',
            name='retake_grades_num',
            field=models.SmallIntegerField(default=crud.models.get_default_retake_num, verbose_name='Number of retakes'),
        ),
    ]
