# Generated by Django 2.0 on 2018-02-13 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.translation


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('crud', '0011_auto_20180208_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='SchoolClass',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('name',), 'verbose_name': 'Student'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='crud.Subject'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese (Brazil)')], default=django.utils.translation.get_language, max_length=25, null=True, verbose_name='Language'),
        ),
    ]
